### ISSUE TITLE
FB15k-Regex and Wiki100-Regex dumps

### ISSUE THREAD

**Issue by migalkin** [dair-iitd/kbi-regex#1]
Hi, it looks like the repo does not provide any download link for the final query datasets, and the preprocessing pipeline has a few hardcoded constants pertaining to the datasets. 
Could you please share the resulting datasets from the paper? For example, Zenodo / Google Drive / Dropbox allow public sharing. 

Thanks!

**Comment by vaibhavad** [comment]
Hi,

The datasets are available via Zenodo. The documentation has been updated to reflect the same - 
https://github.com/dair-iitd/kbi-regex#downloading-datasets

**Comment by migalkin** [comment]
Wonderful, thanks a lot!
